'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VtMBTranslator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property deepl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deepl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property DeepL_net() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("DeepL_net", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property deeplM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deeplM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property deeplV() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deeplV", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property document() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EmptyDatagrid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EmptyDatagrid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folderclosed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folderclosed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folderopen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folderopen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property Microsoft_Bcl_AsyncInterfaces() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Microsoft_Bcl_AsyncInterfaces", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;doc&gt;
        '''    &lt;assembly&gt;
        '''        &lt;name&gt;Microsoft.Bcl.AsyncInterfaces&lt;/name&gt;
        '''    &lt;/assembly&gt;
        '''    &lt;members&gt;
        '''        &lt;member name=&quot;T:System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1&quot;&gt;
        '''            &lt;summary&gt;Provides the core logic for implementing a manual-reset &lt;see cref=&quot;T:System.Threading.Tasks.Sources.IValueTaskSource&quot;/&gt; or &lt;see cref=&quot;T:System.Threading.Tasks.Sources.IValueTaskSource`1&quot;/&gt;.&lt;/summary&gt;
        '''            &lt;typeparam name=&quot;TResult&quot;&gt;&lt;/typeparam&gt;
        '''        &lt;/member&gt; [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Microsoft_Bcl_AsyncInterfaces1() As String
            Get
                Return ResourceManager.GetString("Microsoft_Bcl_AsyncInterfaces1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property Microsoft_Extensions_DependencyInjection() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Microsoft_Extensions_DependencyInjection", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property Microsoft_Extensions_DependencyInjection_Abstractions() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Microsoft_Extensions_DependencyInjection_Abstractions", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;doc&gt;
        '''  &lt;assembly&gt;
        '''    &lt;name&gt;Microsoft.Extensions.DependencyInjection.Abstractions&lt;/name&gt;
        '''  &lt;/assembly&gt;
        '''  &lt;members&gt;
        '''    &lt;member name=&quot;T:Microsoft.Extensions.DependencyInjection.ActivatorUtilities&quot;&gt;
        '''      &lt;summary&gt;Helper code for the various activator services.&lt;/summary&gt;
        '''    &lt;/member&gt;
        '''    &lt;member name=&quot;M:Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateFactory(System.Type,System.Type[])&quot;&gt;
        '''      &lt;summary&gt;Create a delegate that will instantiate  [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Microsoft_Extensions_DependencyInjection_Abstractions1() As String
            Get
                Return ResourceManager.GetString("Microsoft_Extensions_DependencyInjection_Abstractions1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;doc&gt;
        '''  &lt;assembly&gt;
        '''    &lt;name&gt;Microsoft.Extensions.DependencyInjection&lt;/name&gt;
        '''  &lt;/assembly&gt;
        '''  &lt;members&gt;
        '''    &lt;member name=&quot;T:Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory&quot;&gt;
        '''      &lt;summary&gt;Default implementation of &lt;see cref=&quot;T:Microsoft.Extensions.DependencyInjection.IServiceProviderFactory`1&quot; /&gt;.&lt;/summary&gt;
        '''    &lt;/member&gt;
        '''    &lt;member name=&quot;M:Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.#ctor&quot;&gt;
        '''      &lt;summary&gt;Ini [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Microsoft_Extensions_DependencyInjection1() As String
            Get
                Return ResourceManager.GetString("Microsoft_Extensions_DependencyInjection1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property Microsoft_Extensions_Http() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Microsoft_Extensions_Http", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property Microsoft_Extensions_Http_Polly() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Microsoft_Extensions_Http_Polly", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;doc&gt;
        '''    &lt;assembly&gt;
        '''        &lt;name&gt;Microsoft.Extensions.Http.Polly&lt;/name&gt;
        '''    &lt;/assembly&gt;
        '''    &lt;members&gt;
        '''        &lt;member name=&quot;T:Microsoft.Extensions.DependencyInjection.PollyHttpClientBuilderExtensions&quot;&gt;
        '''            &lt;summary&gt;
        '''            Extensions methods for configuring &lt;see cref=&quot;T:Microsoft.Extensions.Http.PolicyHttpMessageHandler&quot;/&gt; message handlers as part of
        '''            and &lt;see cref=&quot;T:System.Net.Http.HttpClient&quot;/&gt; message handler pipeline.
        '''            &lt;/summary&gt;
        '''    [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Microsoft_Extensions_Http_Polly1() As String
            Get
                Return ResourceManager.GetString("Microsoft_Extensions_Http_Polly1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;doc&gt;
        '''  &lt;assembly&gt;
        '''    &lt;name&gt;Microsoft.Extensions.Http&lt;/name&gt;
        '''  &lt;/assembly&gt;
        '''  &lt;members&gt;
        '''    &lt;member name=&quot;T:Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions&quot;&gt;
        '''      &lt;summary&gt;Extension methods for configuring an &lt;see cref=&quot;T:Microsoft.Extensions.DependencyInjection.IHttpClientBuilder&quot; /&gt;&lt;/summary&gt;
        '''    &lt;/member&gt;
        '''    &lt;member name=&quot;M:Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.AddHttpMessageHandler(Microsoft.Extensions. [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Microsoft_Extensions_Http1() As String
            Get
                Return ResourceManager.GetString("Microsoft_Extensions_Http1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property Microsoft_Extensions_Logging() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Microsoft_Extensions_Logging", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property Microsoft_Extensions_Logging_Abstractions() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Microsoft_Extensions_Logging_Abstractions", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;doc&gt;
        '''  &lt;assembly&gt;
        '''    &lt;name&gt;Microsoft.Extensions.Logging.Abstractions&lt;/name&gt;
        '''  &lt;/assembly&gt;
        '''  &lt;members&gt;
        '''    &lt;member name=&quot;T:Microsoft.Extensions.Logging.Abstractions.LogEntry`1&quot;&gt;
        '''      &lt;typeparam name=&quot;TState&quot; /&gt;
        '''    &lt;/member&gt;
        '''    &lt;member name=&quot;M:Microsoft.Extensions.Logging.Abstractions.LogEntry`1.#ctor(Microsoft.Extensions.Logging.LogLevel,System.String,Microsoft.Extensions.Logging.EventId,`0,System.Exception,System.Func{`0,System.Exception,System.String})&quot;&gt; [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Microsoft_Extensions_Logging_Abstractions1() As String
            Get
                Return ResourceManager.GetString("Microsoft_Extensions_Logging_Abstractions1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;doc&gt;
        '''  &lt;assembly&gt;
        '''    &lt;name&gt;Microsoft.Extensions.Logging&lt;/name&gt;
        '''  &lt;/assembly&gt;
        '''  &lt;members&gt;
        '''    &lt;member name=&quot;T:Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions&quot;&gt;
        '''      &lt;summary&gt;Extension methods for setting up logging services in an &lt;see cref=&quot;T:Microsoft.Extensions.DependencyInjection.IServiceCollection&quot; /&gt;.&lt;/summary&gt;
        '''    &lt;/member&gt;
        '''    &lt;member name=&quot;M:Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLog [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Microsoft_Extensions_Logging1() As String
            Get
                Return ResourceManager.GetString("Microsoft_Extensions_Logging1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property Microsoft_Extensions_Options() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Microsoft_Extensions_Options", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;doc&gt;
        '''  &lt;assembly&gt;
        '''    &lt;name&gt;Microsoft.Extensions.Options&lt;/name&gt;
        '''  &lt;/assembly&gt;
        '''  &lt;members&gt;
        '''    &lt;member name=&quot;T:Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions&quot;&gt;
        '''      &lt;summary&gt;Extension methods for adding options services to the DI container.&lt;/summary&gt;
        '''    &lt;/member&gt;
        '''    &lt;member name=&quot;M:Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions.AddOptions(Microsoft.Extensions.DependencyInjection.IServiceCollection)&quot;&gt; [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Microsoft_Extensions_Options1() As String
            Get
                Return ResourceManager.GetString("Microsoft_Extensions_Options1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property Microsoft_Extensions_Primitives() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Microsoft_Extensions_Primitives", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;doc&gt;
        '''  &lt;assembly&gt;
        '''    &lt;name&gt;Microsoft.Extensions.Primitives&lt;/name&gt;
        '''  &lt;/assembly&gt;
        '''  &lt;members&gt;
        '''    &lt;member name=&quot;T:Microsoft.Extensions.Primitives.CancellationChangeToken&quot;&gt;
        '''      &lt;summary&gt;A &lt;see cref=&quot;T:Microsoft.Extensions.Primitives.IChangeToken&quot; /&gt; implementation using &lt;see cref=&quot;T:System.Threading.CancellationToken&quot; /&gt;.&lt;/summary&gt;
        '''    &lt;/member&gt;
        '''    &lt;member name=&quot;M:Microsoft.Extensions.Primitives.CancellationChangeToken.#ctor(System.Threading.CancellationToke [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Microsoft_Extensions_Primitives1() As String
            Get
                Return ResourceManager.GetString("Microsoft_Extensions_Primitives1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property Polly() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Polly", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property Polly_Extensions_Http() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Polly_Extensions_Http", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;doc&gt;
        '''    &lt;assembly&gt;
        '''        &lt;name&gt;Polly.Extensions.Http&lt;/name&gt;
        '''    &lt;/assembly&gt;
        '''    &lt;members&gt;
        '''        &lt;member name=&quot;T:Polly.Extensions.Http.HttpPolicyExtensions&quot;&gt;
        '''            &lt;summary&gt;
        '''            Contains opinionated convenience methods for configuring policies to handle conditions typically representing transient faults when making &lt;see cref=&quot;T:System.Net.Http.HttpClient&quot;/&gt; requests.
        '''            &lt;/summary&gt;
        '''        &lt;/member&gt;
        '''        &lt;member name=&quot;M:Polly.Extensions.Http.Htt [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Polly_Extensions_Http1() As String
            Get
                Return ResourceManager.GetString("Polly_Extensions_Http1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;doc&gt;
        '''    &lt;assembly&gt;
        '''        &lt;name&gt;Polly&lt;/name&gt;
        '''    &lt;/assembly&gt;
        '''    &lt;members&gt;
        '''        &lt;member name=&quot;T:Polly.AsyncPolicy&quot;&gt;
        '''            &lt;summary&gt;
        '''            Transient exception handling policies that can be applied to asynchronous delegates
        '''            &lt;/summary&gt;
        '''        &lt;/member&gt;
        '''        &lt;member name=&quot;M:Polly.AsyncPolicy.WithPolicyKey(System.String)&quot;&gt;
        '''            &lt;summary&gt;
        '''            Sets the PolicyKey for this &lt;see cref=&quot;T:Polly.AsyncPolicy&quot;/&gt; instance.
        '''            &lt;rem [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Polly1() As String
            Get
                Return ResourceManager.GetString("Polly1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property System_Diagnostics_DiagnosticSource() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("System_Diagnostics_DiagnosticSource", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;doc&gt;
        '''  &lt;assembly&gt;
        '''    &lt;name&gt;System.Diagnostics.DiagnosticSource&lt;/name&gt;
        '''  &lt;/assembly&gt;
        '''  &lt;members&gt;
        '''    &lt;member name=&quot;T:System.Diagnostics.Activity&quot;&gt;
        '''      &lt;summary&gt;Represents an operation with context to be used for logging.&lt;/summary&gt;
        '''    &lt;/member&gt;
        '''    &lt;member name=&quot;M:System.Diagnostics.Activity.#ctor(System.String)&quot;&gt;
        '''      &lt;summary&gt;Initializes a new instance of the &lt;see cref=&quot;T:System.Diagnostics.Activity&quot; /&gt; class.&lt;/summary&gt;
        '''      &lt;param name=&quot;operationName [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property System_Diagnostics_DiagnosticSource1() As String
            Get
                Return ResourceManager.GetString("System_Diagnostics_DiagnosticSource1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property System_Threading_Tasks_Extensions() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("System_Threading_Tasks_Extensions", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;doc&gt;
        '''  &lt;assembly&gt;
        '''    &lt;name&gt;System.Threading.Tasks.Extensions&lt;/name&gt;
        '''  &lt;/assembly&gt;
        '''  &lt;members&gt;
        '''    &lt;member name=&quot;T:System.Runtime.CompilerServices.ValueTaskAwaiter`1&quot;&gt;
        '''      &lt;typeparam name=&quot;TResult&quot;&gt;&lt;/typeparam&gt;
        '''    &lt;/member&gt;
        '''    &lt;member name=&quot;M:System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult&quot;&gt;
        '''      &lt;returns&gt;&lt;/returns&gt;
        '''    &lt;/member&gt;
        '''    &lt;member name=&quot;P:System.Runtime.CompilerServices.ValueTaskAwaiter`1.IsCompleted&quot;&gt;
        '''      &lt;returns&gt;&lt;/returns&gt;        ''' [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property System_Threading_Tasks_Extensions1() As String
            Get
                Return ResourceManager.GetString("System_Threading_Tasks_Extensions1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property System_ValueTuple() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("System_ValueTuple", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;doc&gt;
        '''    &lt;assembly&gt;
        '''        &lt;name&gt;System.ValueTuple&lt;/name&gt;
        '''    &lt;/assembly&gt;
        '''    &lt;members&gt;
        '''    &lt;/members&gt;
        '''&lt;/doc&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property System_ValueTuple1() As String
            Get
                Return ResourceManager.GetString("System_ValueTuple1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property undo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("undo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
